version: '3.4'

services:
  modalmaisdb:
    networks:
      - webproxy
    image: mongo
  
  transacaodb:
    networks:
      - webproxy
    image: postgres

  modalmais.api:
    networks:
      - webproxy
    image: ${DOCKER_REGISTRY-}modalmaisapi
    build:
      context: .
      dockerfile: src/Modalmais.API/Dockerfile

  modalmais.transacoes.api:
    networks:
      - webproxy
    image: ${DOCKER_REGISTRY-}modalmaistransacoesapi
    build:
      context: .
      dockerfile: src/Modalmais.Transacoes.API/Dockerfile

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - webproxy
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - webproxy
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  redis:
    image: redis
    command: redis-server
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - webproxy

networks:
  webproxy:
    driver: bridge


volumes:
  mongo_data:
  postgres_data:
