version: '3.4'

services:
  modalmaisdb:
    container_name: mongodb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  transacaodb:
    container_name: postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=rootvaivoa
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data/

  modalmais.api:
    container_name: Modalmais.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - modalmaisdb
    ports:
      - "5001:80"

  modalmais.transacoes.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "Api-StringBd-Postgres:Host=transacaodb;Database=modalmais;Username=postgres;Password=rootvaivoa"
    ports:
      - "5101:80"
    depends_on:
      - transacaodb
