namespace Modalmais.Business.Models.Enums
{
    public enum DDDBrasil
    {

        SP_Capital = 11,
        SP_SaoJoseDosCampos = 12,
        SP_Santos = 13,
        SP_Bauru = 14,
        SP_Sorocoba = 15,
        SP_RibeiraoPreto = 16,
        SP_SaoJoseDoRioPreto = 17,
        SP_PresidentePrudente = 18,
        SP_Campinas = 19,
        RJ_RioDeJaneiro = 21,
        RJ_CamposDosGoytacazes = 22,
        SP_VoltaRedonda = 24,
        ES_Vitoria = 27,
        ES_CachoeiroDeItapemirim = 28,
        MG_BeloHorizonte = 31,
        MG_JuizDeFora = 32,
        MG_Governador = 33,
        MG_Uberlandia = 34,
        MG_PocosDeCaldas = 35,
        MG_Divinopolis = 37,
        MG_MonteClaros = 38,
        PR_Curitiba = 41,
        PR_PontaGrossa = 42,
        PR_Londrina = 43,
        PR_Maringa = 44,
        PR_FozDoIguacu = 45,
        PR_PatoBranco = 46,
        SC_Joinvile = 47,
        SC_Florianopolis = 48,
        SC_Chapecop = 49,
        RS_PortoAlegre = 51,
        RS_Peloras = 53,
        RS_CaxuasDoSul = 54,
        RS_SantaMaria = 55,
        DF_Brasilia = 61,
        GO_Goiania = 62,
        TO_Palmas = 63,
        GO_RioVerde = 64,
        MT_Cuiaba = 65,
        MT_Rondonopolis = 66,
        MT_CampoGrande = 67,
        AC_RioBranco = 68,
        RO_PortoVelho = 69,
        BA_Salvador = 71,
        BA_Ileus = 73,
        BA_Juazeiro = 74,
        BA_FeiraDeSantana = 75,
        BA_Barreiras = 77,
        SE_Aracaju = 79,
        RE_Recife = 81,
        AL_Maceio = 82,
        PB_JoaoPessoa = 83,
        RN_Natal = 84,
        CE_Fortaleza = 85,
        PI_Teresina = 86,
        PE_Petrolina = 87,
        CE_Juazeiro = 88,
        PI_Picos = 89,
        PA_Belem = 91,
        AM_Manaus = 92,
        PA_Santarem = 93,
        PA_Maraba = 94,
        RR_BoaVista = 95,
        AP_Macapa = 96,
        AM_Coari = 97,
        MA_SaoLuis = 98,
        MA_Imperatiz = 99,

    }
}
