name: dotnet package

on: 
  push:
    branches:
      - feat/img_cloud
  pull_request:
    branches:
      - feat/img_cloud

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Test
        run: dotnet test ~/Modalmais/test/Modalmais.Test/Modalmais.Test.csproj
